In [2]:
import pandas as pd


train_df = pd.read_csv("nih-cxr-lt_single-label_train.csv")
test_df = pd.read_csv("nih-cxr-lt_single-label_test.csv")
val_df = pd.read_csv("nih-cxr-lt_single-label_balanced-val.csv")

train_df["Split"] = "TRAIN"
val_df["Split"] = "VAL"
test_df["Split"] = "TEST"

df = pd.concat([train_df, val_df, test_df])
df

,id,Atelectasis,Cardiomegaly,Consolidation,Edema,Effusion,Emphysema,Fibrosis,Hernia,Infiltration,...,Pneumonia,Pneumothorax,Pneumoperitoneum,Pneumomediastinum,Subcutaneous Emphysema,Tortuous Aorta,Calcification of the Aorta,No Finding,subject_id,Split
0,00000001_000.png,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,TRAIN
1,00000002_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,TRAIN
2,00000005_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
3,00000005_001.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
4,00000005_002.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20274,00030777_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30777,TEST
20275,00030782_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30782,TEST
20276,00030789_000.png,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,30789,TEST
20277,00030797_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30797,TEST
20278,00030799_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30799,TEST

In [3]:
df = df.rename(columns={"id": "path", "subject_id": "id"})
df["path"] = df["path"].apply(lambda x: "images/" + x)
df

,path,Atelectasis,Cardiomegaly,Consolidation,Edema,Effusion,Emphysema,Fibrosis,Hernia,Infiltration,...,Pneumonia,Pneumothorax,Pneumoperitoneum,Pneumomediastinum,Subcutaneous Emphysema,Tortuous Aorta,Calcification of the Aorta,No Finding,id,Split
0,images/00000001_000.png,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,TRAIN
1,images/00000002_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,2,TRAIN
2,images/00000005_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
3,images/00000005_001.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
4,images/00000005_002.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,5,TRAIN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20274,images/00030777_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30777,TEST
20275,images/00030782_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30782,TEST
20276,images/00030789_000.png,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,30789,TEST
20277,images/00030797_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30797,TEST
20278,images/00030799_000.png,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,30799,TEST

In [ ]:
df.to_csv("cxr14-lt.csv")